# Generated by Django 2.2.4 on 2019-08-12 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beauty', '0005_auto_20190809_0022'),
        ('accounts', '0002_auto_20190811_0050'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='cosmetic',
            field=models.ManyToManyField(to='beauty.Cosmetic'),
        ),
    ]
