# Generated by Django 2.2.4 on 2019-08-12 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_cosmetic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='realname',
        ),
    ]
