# Generated by Django 2.2.4 on 2019-08-13 03:31

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20190813_1230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='birth',
            field=models.DateField(default=datetime.datetime(2019, 8, 13, 3, 31, 23, 394130, tzinfo=utc)),
        ),
    ]
