# Generated by Django 2.2.4 on 2019-08-17 05:35

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20190813_1231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='birth',
            field=models.DateField(default=datetime.datetime(2019, 8, 17, 5, 35, 54, 708696, tzinfo=utc)),
        ),
    ]
