# Generated by Django 2.2.4 on 2019-08-06 03:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cosmetic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(db_index=True, max_length=240)),
                ('name', models.CharField(db_index=True, max_length=240)),
            ],
        ),
        migrations.CreateModel(
            name='Youtuber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('yt_url', models.URLField()),
                ('upload_at', models.DateField()),
                ('hits', models.IntegerField()),
                ('cosmetic', models.ManyToManyField(to='beauty.Cosmetic')),
                ('youtuber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='beauty.Youtuber')),
            ],
        ),
    ]
