# Generated by Django 2.2.4 on 2019-08-06 07:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('beauty', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='video',
            options={'ordering': ['hits', 'title']},
        ),
    ]
