# Generated by Django 2.2.4 on 2019-08-08 07:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('beauty', '0002_auto_20190806_1607'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bigcate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='cosmetic',
            name='category',
        ),
        migrations.CreateModel(
            name='Smallcate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('bigcate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='beauty.Bigcate')),
            ],
        ),
    ]
