# Generated by Django 2.2.4 on 2019-08-08 07:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('beauty', '0003_auto_20190808_1607'),
    ]

    operations = [
        migrations.AddField(
            model_name='cosmetic',
            name='category',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='beauty.Smallcate'),
            preserve_default=False,
        ),
    ]
