# Generated by Django 2.2.4 on 2019-08-08 15:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('beauty', '0004_cosmetic_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='bigcate',
            name='eng_name',
            field=models.CharField(default='temp', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='smallcate',
            name='eng_name',
            field=models.CharField(default='temp', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cosmetic',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='beauty.Smallcate', verbose_name='category'),
        ),
        migrations.AlterField(
            model_name='smallcate',
            name='bigcate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='beauty.Bigcate', verbose_name='bigcate'),
        ),
        migrations.AlterField(
            model_name='video',
            name='youtuber',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='beauty.Youtuber', verbose_name='youtuber'),
        ),
    ]
